### ISSUE TITLE
Possibly not compatible to current version?

### ISSUE THREAD

**Issue by cswords** [szagoruyko/cutorch-rtc#2]
I am running on ppc64 with cuda acceleration.
Got these in installation:

---

cd build && make install
[100%] Building NVCC (Device) object CMakeFiles/cutorchrtc.dir//./cutorchrtc_generated_apply.cu.o
/tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/apply.cu(201): error: too few arguments for class template "TensorInfo"

/tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/apply.cu(260): error: too few arguments for class template "TensorInfo"

/tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/apply.cu(261): error: too few arguments for class template "TensorInfo"

/tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/apply.cu(325): error: too few arguments for class template "TensorInfo"

/tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/apply.cu(326): error: too few arguments for class template "TensorInfo"

/tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/apply.cu(327): error: too few arguments for class template "TensorInfo"

/tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/apply.cu(401): error: identifier "THC_overlappingIndices" is undefined

/tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/apply.cu(444): error: identifier "THC_canUse32BitIndexMath" is undefined

/tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/apply.cu(445): error: too few arguments for class template "TensorInfo"

/tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/apply.cu(445): error: expected a ")"

/tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/apply.cu(449): error: too few arguments for class template "TensorInfo"

/tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/apply.cu(449): error: expected a ")"

/tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/apply.cu(521): error: identifier "THC_overlappingIndices" is undefined

/tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/apply.cu(587): error: identifier "THC_canUse32BitIndexMath" is undefined

/tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/apply.cu(589): error: too few arguments for class template "TensorInfo"

/tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/apply.cu(589): error: expected a ")"

/tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/apply.cu(590): error: too few arguments for class template "TensorInfo"

/tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/apply.cu(590): error: expected a ")"

/tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/apply.cu(594): error: too few arguments for class template "TensorInfo"

/tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/apply.cu(594): error: expected a ")"

/tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/apply.cu(595): error: too few arguments for class template "TensorInfo"

/tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/apply.cu(595): error: expected a ")"

/tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/apply.cu(683): error: identifier "THC_overlappingIndices" is undefined

/tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/apply.cu(772): error: identifier "THC_canUse32BitIndexMath" is undefined

/tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/apply.cu(775): error: too few arguments for class template "TensorInfo"

/tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/apply.cu(775): error: expected a ")"

/tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/apply.cu(776): error: too few arguments for class template "TensorInfo"

/tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/apply.cu(776): error: expected a ")"

/tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/apply.cu(777): error: too few arguments for class template "TensorInfo"

/tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/apply.cu(777): error: expected a ")"

/tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/apply.cu(781): error: too few arguments for class template "TensorInfo"

/tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/apply.cu(781): error: expected a ")"

/tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/apply.cu(782): error: too few arguments for class template "TensorInfo"

/tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/apply.cu(782): error: expected a ")"

/tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/apply.cu(783): error: too few arguments for class template "TensorInfo"

/tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/apply.cu(783): error: expected a ")"

36 errors detected in the compilation of "/tmp/tmpxft_0000e2e6_00000000-7_apply.cpp1.ii".
CMake Error at cutorchrtc_generated_apply.cu.o.cmake:267 (message):
  Error generating file
  /tmp/luarocks_cutorch-rtc-scm-1-8738/cutorch-rtc/build/CMakeFiles/cutorchrtc.dir//./cutorchrtc_generated_apply.cu.o

make[2]: **\* [CMakeFiles/cutorchrtc.dir/./cutorchrtc_generated_apply.cu.o] Error 1
make[1]: **\* [CMakeFiles/cutorchrtc.dir/all] Error 2
make: **\* [all] Error 2

Error: Build error: Failed installing.

---

Thanks a lot if these could be fixed. Cheers.

**Comment by szagoruyko** [comment]
try types branch, it has incomplete support (launchPTX and apply1, no apply2 and apply3)

**Comment by cswords** [comment]
@szagoruyko Thanks for quick reply~ tried actually.. with no luck. 

---

cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/root/torch-distro/install/bin/.." -DCMAKE_INSTALL_PREFIX="/root/torch-distro/install/lib/luarocks/rocks/cutorch-rtc/scm-1"

-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Torch7 in /root/torch-distro/install
-- Found CUDA: /usr/local/cuda (found suitable version "7.5", minimum required is "7.0")
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/build
cd build && make install
[100%] Building NVCC (Device) object CMakeFiles/cutorchrtc.dir//./cutorchrtc_generated_apply.cu.o
/tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/apply.cu(201): error: too few arguments for class template "TensorInfo"

/tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/apply.cu(260): error: too few arguments for class template "TensorInfo"

/tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/apply.cu(261): error: too few arguments for class template "TensorInfo"

/tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/apply.cu(325): error: too few arguments for class template "TensorInfo"

/tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/apply.cu(326): error: too few arguments for class template "TensorInfo"

/tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/apply.cu(327): error: too few arguments for class template "TensorInfo"

/tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/apply.cu(401): error: identifier "THC_overlappingIndices" is undefined

/tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/apply.cu(444): error: identifier "THC_canUse32BitIndexMath" is undefined

/tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/apply.cu(445): error: too few arguments for class template "TensorInfo"

/tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/apply.cu(445): error: expected a ")"

/tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/apply.cu(449): error: too few arguments for class template "TensorInfo"

/tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/apply.cu(449): error: expected a ")"

/tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/apply.cu(521): error: identifier "THC_overlappingIndices" is undefined

/tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/apply.cu(587): error: identifier "THC_canUse32BitIndexMath" is undefined

/tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/apply.cu(589): error: too few arguments for class template "TensorInfo"

/tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/apply.cu(589): error: expected a ")"

/tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/apply.cu(590): error: too few arguments for class template "TensorInfo"

/tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/apply.cu(590): error: expected a ")"

/tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/apply.cu(594): error: too few arguments for class template "TensorInfo"

/tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/apply.cu(594): error: expected a ")"

/tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/apply.cu(595): error: too few arguments for class template "TensorInfo"

/tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/apply.cu(595): error: expected a ")"

/tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/apply.cu(683): error: identifier "THC_overlappingIndices" is undefined

/tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/apply.cu(772): error: identifier "THC_canUse32BitIndexMath" is undefined

/tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/apply.cu(775): error: too few arguments for class template "TensorInfo"

/tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/apply.cu(775): error: expected a ")"

/tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/apply.cu(776): error: too few arguments for class template "TensorInfo"

/tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/apply.cu(776): error: expected a ")"

/tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/apply.cu(777): error: too few arguments for class template "TensorInfo"

/tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/apply.cu(777): error: expected a ")"

/tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/apply.cu(781): error: too few arguments for class template "TensorInfo"

/tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/apply.cu(781): error: expected a ")"

/tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/apply.cu(782): error: too few arguments for class template "TensorInfo"

/tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/apply.cu(782): error: expected a ")"

/tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/apply.cu(783): error: too few arguments for class template "TensorInfo"

/tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/apply.cu(783): error: expected a ")"

36 errors detected in the compilation of "/tmp/tmpxft_0000e4df_00000000-7_apply.cpp1.ii".
CMake Error at cutorchrtc_generated_apply.cu.o.cmake:267 (message):
  Error generating file
  /tmp/luarocks_cutorch-rtc-scm-1-9075/cutorch-rtc/build/CMakeFiles/cutorchrtc.dir//./cutorchrtc_generated_apply.cu.o

make[2]: **\* [CMakeFiles/cutorchrtc.dir/./cutorchrtc_generated_apply.cu.o] Error 1
make[1]: **\* [CMakeFiles/cutorchrtc.dir/all] Error 2
make: **\* [all] Error 2

Error: Build error: Failed installing.

**Comment by szagoruyko** [comment]
@cswords are you sure you did `luarocks make` and not `luarocks install`?

**Comment by cswords** [comment]
@szagoruyko thanks a lot! I previously just did luarocks install thefileingithub.rockspec. And now I just tried cloning the types branch and did luarocks make and it worked~
